-- MySQL Script generated by MySQL Workbench
-- Sun Nov 24 19:46:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_mos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_mos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_mos` DEFAULT CHARACTER SET utf8mb4 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `db_mos` ;

-- -----------------------------------------------------
-- Table `db_mos`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(13) NOT NULL,
  `p_nombre` VARCHAR(20) NOT NULL,
  `s_nombre` VARCHAR(20) NULL,
  `p_apellido` VARCHAR(20) NOT NULL,
  `s_apellido` VARCHAR(20) NULL,
  `genero` VARCHAR(1) NOT NULL,
  `f_nac` DATE NOT NULL,
  `email` VARCHAR(100) NULL,
  `f_creacion` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idpersona` INT NOT NULL,
  `usuario` VARCHAR(30) NOT NULL,
  `clave` VARCHAR(64) NOT NULL,
  `rol` VARCHAR(30) NOT NULL,
  `img` VARCHAR(45) NULL,
  `i_fallidos` INT(1) NOT NULL,
  `estatus` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  INDEX `usuario_persona_idx` (`idpersona` ASC) VISIBLE,
  CONSTRAINT `usuario_persona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `db_mos`.`persona` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`p_seguridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`p_seguridad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`u_respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`u_respuesta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idpregunta` INT NOT NULL,
  `respuesta` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `respuesta_usuario_idx` (`idusuario` ASC) VISIBLE,
  INDEX `rusuario_pregunta_idx` (`idpregunta` ASC) VISIBLE,
  CONSTRAINT `rusuario_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `db_mos`.`usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `rusuario_pregunta`
    FOREIGN KEY (`idpregunta`)
    REFERENCES `db_mos`.`p_seguridad` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iso` CHAR(2) NULL,
  `pais` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `iso_UNIQUE` (`iso` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idpais` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `estado_pais_idx` (`idpais` ASC) VISIBLE,
  CONSTRAINT `estado_pais`
    FOREIGN KEY (`idpais`)
    REFERENCES `db_mos`.`pais` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`municipio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idestado` INT NOT NULL,
  `municipio` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `municipio_estado_idx` (`idestado` ASC) VISIBLE,
  CONSTRAINT `municipio_estado`
    FOREIGN KEY (`idestado`)
    REFERENCES `db_mos`.`estado` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`parroquia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`parroquia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idmunicipio` INT NOT NULL,
  `parroquia` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `parroquia_municipio_idx` (`idmunicipio` ASC) VISIBLE,
  CONSTRAINT `parroquia_municipio`
    FOREIGN KEY (`idmunicipio`)
    REFERENCES `db_mos`.`municipio` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`telefono` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idpersona` INT NULL,
  `telefono` CHAR(12) NULL,
  `tipo` CHAR(1) NULL COMMENT 'M - Móvil\nF - Fijo ',
  PRIMARY KEY (`id`),
  INDEX `persona_telefono_idx` (`idpersona` ASC) VISIBLE,
  CONSTRAINT `persona_telefono`
    FOREIGN KEY (`idpersona`)
    REFERENCES `db_mos`.`persona` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`direccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idpersona` INT NULL,
  `idparroquia` INT NULL,
  `direccion` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `direccion_persona_idx` (`idpersona` ASC) VISIBLE,
  INDEX `direccion_parroquia_idx` (`idparroquia` ASC) VISIBLE,
  CONSTRAINT `direccion_persona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `db_mos`.`persona` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `direccion_parroquia`
    FOREIGN KEY (`idparroquia`)
    REFERENCES `db_mos`.`parroquia` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`permiso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `permiso` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`representante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`representante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idpersona` INT NULL,
  `instruccion` VARCHAR(20) NULL,
  `oficio` VARCHAR(45) NULL,
  `estatus` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `representante_persona_idx` (`idpersona` ASC) VISIBLE,
  CONSTRAINT `representante_persona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `db_mos`.`persona` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`usuario_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`usuario_permiso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NULL,
  `idpermiso` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_permiso_idx` (`idusuario` ASC) VISIBLE,
  INDEX `usuario_permiso_permiso_idx` (`idpermiso` ASC) VISIBLE,
  CONSTRAINT `usuario_permiso`
    FOREIGN KEY (`idusuario`)
    REFERENCES `db_mos`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `usuario_permiso_permiso`
    FOREIGN KEY (`idpermiso`)
    REFERENCES `db_mos`.`permiso` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`periodo_escolar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`periodo_escolar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `periodo` VARCHAR(9) NULL,
  `estatus` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`ambiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`ambiente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ambiente` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`grado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grado` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`seccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `seccion` TINYTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`planificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`planificacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idperiodo_escolar` INT NULL,
  `idambiente` INT NULL,
  `idgrado` INT NULL,
  `idseccion` INT NULL,
  `iddocente` INT NULL,
  `cupo` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idperiodo_escolar_periodo_escolar_idx` (`idperiodo_escolar` ASC) VISIBLE,
  INDEX `idambiente_ambiente_idx` (`idambiente` ASC) VISIBLE,
  INDEX `idgrado_grado_idx` (`idgrado` ASC) VISIBLE,
  INDEX `idseccion_seccion_idx` (`idseccion` ASC) VISIBLE,
  INDEX `iddocente_docente_idx` (`iddocente` ASC) VISIBLE,
  CONSTRAINT `idperiodo_escolar_periodo_escolar`
    FOREIGN KEY (`idperiodo_escolar`)
    REFERENCES `db_mos`.`periodo_escolar` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idambiente_ambiente`
    FOREIGN KEY (`idambiente`)
    REFERENCES `db_mos`.`ambiente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idgrado_grado`
    FOREIGN KEY (`idgrado`)
    REFERENCES `db_mos`.`grado` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idseccion_seccion`
    FOREIGN KEY (`idseccion`)
    REFERENCES `db_mos`.`seccion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `iddocente_docente`
    FOREIGN KEY (`iddocente`)
    REFERENCES `db_mos`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`personal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idpersona` INT NOT NULL,
  `cargo` VARCHAR(30) NOT NULL,
  `estatus` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`historial_directivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`historial_directivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idpersonal` INT NULL,
  `cargo` VARCHAR(30) NULL,
  `periodo` CHAR(9) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`estudiante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idpersona` INT NULL,
  `estatus` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `estudiante_persona_idx` (`idpersona` ASC) VISIBLE,
  CONSTRAINT `estudiante_persona`
    FOREIGN KEY (`idpersona`)
    REFERENCES `db_mos`.`persona` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`aspecto_fisiologico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`aspecto_fisiologico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idestudiante` INT NULL,
  `todas_vacunas` TINYINT(1) NULL COMMENT '0-No 1-Si',
  `peso` DECIMAL(2,2) NULL,
  `talla` DECIMAL(1,2) NULL,
  `alergico` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `aspecto_fisiologico_estudiante_idx` (`idestudiante` ASC) VISIBLE,
  CONSTRAINT `aspecto_fisiologico_estudiante`
    FOREIGN KEY (`idestudiante`)
    REFERENCES `db_mos`.`estudiante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`diversidad_funcional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`diversidad_funcional` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idestudiante` INT NULL,
  `diversidad` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `diversidad_funcional_estudiante_idx` (`idestudiante` ASC) VISIBLE,
  CONSTRAINT `diversidad_funcional_estudiante`
    FOREIGN KEY (`idestudiante`)
    REFERENCES `db_mos`.`estudiante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`enfermedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`enfermedad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idestudiante` INT NULL,
  `enfermedad` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `enfermedad_estudiante_idx` (`idestudiante` ASC) VISIBLE,
  CONSTRAINT `enfermedad_estudiante`
    FOREIGN KEY (`idestudiante`)
    REFERENCES `db_mos`.`estudiante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`aspecto_socioeconomico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`aspecto_socioeconomico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idestudiante` INT NULL,
  `tipo_vivienda` VARCHAR(10) NULL,
  `grupo_familiar` TINYINT(2) NULL,
  `ingreso_mensual` DECIMAL(11,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `aspecto_socioeconomico_estudiante_idx` (`idestudiante` ASC) VISIBLE,
  CONSTRAINT `aspecto_socioeconomico_estudiante`
    FOREIGN KEY (`idestudiante`)
    REFERENCES `db_mos`.`estudiante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`sosten_hogar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`sosten_hogar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idestudiante` INT NULL,
  `sosten` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `sosten_hogar_estudiante_idx` (`idestudiante` ASC) VISIBLE,
  CONSTRAINT `sosten_hogar_estudiante`
    FOREIGN KEY (`idestudiante`)
    REFERENCES `db_mos`.`estudiante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`lugar_nacimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`lugar_nacimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idestudiante` INT NULL,
  `idparroquia` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `lugar_nacimiento_estudiante_idx` (`idestudiante` ASC) VISIBLE,
  CONSTRAINT `lugar_nacimiento_estudiante`
    FOREIGN KEY (`idestudiante`)
    REFERENCES `db_mos`.`estudiante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`canaima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`canaima` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idestudiante` INT NULL,
  `posee_canaima` TINYINT(1) NULL,
  `condicion` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `canaima_estudiante_idx` (`idestudiante` ASC) VISIBLE,
  CONSTRAINT `canaima_estudiante`
    FOREIGN KEY (`idestudiante`)
    REFERENCES `db_mos`.`estudiante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`inscripcion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idplanificacion` INT NULL,
  `idestudiante` INT NULL,
  `condicion` VARCHAR(15) NULL,
  `estatus` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `idplanificacion_planificacion_idx` (`idplanificacion` ASC) VISIBLE,
  INDEX `idestudiante_estudiante_idx` (`idestudiante` ASC) VISIBLE,
  CONSTRAINT `idplanificacion_planificacion`
    FOREIGN KEY (`idplanificacion`)
    REFERENCES `db_mos`.`planificacion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idestudiante_estudiante`
    FOREIGN KEY (`idestudiante`)
    REFERENCES `db_mos`.`estudiante` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `db_mos`.`boletin_final`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`boletin_final` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idinscripcion` INT NULL,
  `nota_literal` CHAR(1) NULL,
  `descripcion_final` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `idinscipcion_inscripcion_idx` (`idinscripcion` ASC) VISIBLE,
  CONSTRAINT `idinscipcion_inscripcion`
    FOREIGN KEY (`idinscripcion`)
    REFERENCES `db_mos`.`inscripcion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`escuela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`escuela` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cod_dea` CHAR(10) NULL,
  `cod_dependencia` CHAR(9) NULL,
  `cod_estadistico` CHAR(6) NULL,
  `cod_electoral` CHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_mos`.`periodo_inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`periodo_inscripcion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idperiodo_escolar` INT NULL,
  `inicio` DATE NULL,
  `fin` DATE NULL,
  `estatus` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `idperiodo_escolar_periodo_escolar_idx` (`idperiodo_escolar` ASC) VISIBLE,
  CONSTRAINT `idperiodo_escolar_periodo_escolar`
    FOREIGN KEY (`idperiodo_escolar`)
    REFERENCES `db_mos`.`periodo_escolar` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `db_mos` ;

-- -----------------------------------------------------
-- Placeholder table for view `db_mos`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_mos`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `db_mos`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_mos`.`view1`;
USE `db_mos`;

USE `db_mos`;

DELIMITER $$
USE `db_mos`$$
CREATE DEFINER = CURRENT_USER TRIGGER `db_mos`.`periodo_escolar_AFTER_UPDATE` AFTER UPDATE ON `periodo_escolar` FOR EACH ROW
BEGIN
Update inscripcion set estatus = 0;
END$$

USE `db_mos`$$
CREATE DEFINER = CURRENT_USER TRIGGER `db_mos`.`inscripcion_AFTER_INSERT` AFTER INSERT ON `inscripcion` FOR EACH ROW
BEGIN
UPDATE planificacion SET cupo = cupo-1;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
